// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDPhzM3NPwM9a9Aqfcbh378AiamtnJuok',
    appId: '1:656444096326:web:1e3b38e83ceaf3ef7bef47',
    messagingSenderId: '656444096326',
    projectId: 'sufypay-2c639',
    authDomain: 'sufypay-2c639.firebaseapp.com',
    storageBucket: 'sufypay-2c639.firebasestorage.app',
    measurementId: 'G-CS7WWWC6TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-jqGjPsYWhGipxhdDeBs_B0lFK-SbOE',
    appId: '1:656444096326:android:c3740ddaa8cc2b177bef47',
    messagingSenderId: '656444096326',
    projectId: 'sufypay-2c639',
    storageBucket: 'sufypay-2c639.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgC_EJfm4zptLOaiEEE5IzHyGet2_WGI8',
    appId: '1:656444096326:ios:5089a9c4527a7cc27bef47',
    messagingSenderId: '656444096326',
    projectId: 'sufypay-2c639',
    storageBucket: 'sufypay-2c639.firebasestorage.app',
    iosBundleId: 'com.example.sufypay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgC_EJfm4zptLOaiEEE5IzHyGet2_WGI8',
    appId: '1:656444096326:ios:5089a9c4527a7cc27bef47',
    messagingSenderId: '656444096326',
    projectId: 'sufypay-2c639',
    storageBucket: 'sufypay-2c639.firebasestorage.app',
    iosBundleId: 'com.example.sufypay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDPhzM3NPwM9a9Aqfcbh378AiamtnJuok',
    appId: '1:656444096326:web:5e654c52afcda2bb7bef47',
    messagingSenderId: '656444096326',
    projectId: 'sufypay-2c639',
    authDomain: 'sufypay-2c639.firebaseapp.com',
    storageBucket: 'sufypay-2c639.firebasestorage.app',
    measurementId: 'G-JQP0GPCMEF',
  );
}
